const Constants = {
  USER_SIGNED_IN: 'USER_SIGNED_IN',
  CURRENT_USER: 'CURRENT_USER',
  CURRENT_USER_FETCHING: 'CURRENT_USER_FETCHING',
  USER_SIGNED_OUT: 'USER_SIGNED_OUT',
  SESSIONS_ERROR: 'SESSIONS_ERROR',
  REGISTRATIONS_ERROR: 'REGISTRATIONS_ERROR',

  LEADERBOARD_FETCHING: 'LEADERBOARD_FETCHING',
  LEADERBOARD_RECEIVED: 'LEADERBOARD_RECEIVED',
  LEADERBOARD_ERROR: 'LEADERBOARD_ERROR',

  USER_FETCHING: 'USER_FETCHING',
  USER_RECEIVED: 'USER_RECEIVED',
  USER_ERROR: 'USER_ERROR',

  VERIFY_EMAIL_LOADING: 'VERIFY_EMAIL_LOADING',
  VERIFY_EMAIL_COMPLETED: 'VERIFY_EMAIL_COMPLETED',
  VERIFY_EMAIL_ERROR: 'VERIFY_EMAIL_ERROR',

  RESEND_VERIFICATION_EMAIL_LOADING: 'RESEND_VERIFICATION_EMAIL_LOADING',
  RESEND_VERIFICATION_EMAIL_COMPLETED: 'RESEND_VERIFICATION_EMAIL_COMPLETED',
  RESEND_VERIFICATION_EMAIL_ERROR: 'RESEND_VERIFICATION_EMAIL_ERROR',

  BEATMAPSET_FETCHING: 'BEATMAPSET_FETCHING',
  BEATMAPSET_RECEIVED: 'BEATMAPSET_RECEIVED',
  BEATMAPSET_ERROR: 'BEATMAPSET_ERROR',
  BEATMAPSET_RESET: 'BEATMAPSET_RESET',

  BOARDS_FETCHING: 'BOARDS_FETCHING',
  BOARDS_SHOW_FORM: 'BOARDS_SHOW_FORM',
  BOARDS_RECEIVED: 'BOARDS_RECEIVED',
  BOARDS_SET_CURRENT_BOARD: 'BOARDS_SET_CURRENT_BOARD',
  BOARDS_CREATE_ERROR: 'BOARDS_CREATE_ERROR',
  BOARDS_RESET: 'BOARDS_RESET',
  BOARDS_FULL_RESET: 'BOARDS_FULL_RESET',
  BOARDS_ADDED: 'BOARDS_ADDED',
  BOARDS_NEW_BOARD_CREATED: 'BOARDS_NEW_BOARD_CREATED',

  CURRENT_BOARD_FETHING: 'CURRENT_BOARD_FETHING',
  CURRENT_BOARD_CONNECTED_USERS: 'CURRENT_BOARD_CONNECTED_USERS',
  CURRENT_BOARD_CONNECTED_TO_CHANNEL: 'CURRENT_BOARD_CONNECTED_TO_CHANNEL',
  CURRENT_BOARD_RESET: 'CURRENT_BOARD_RESET',
  CURRENT_BOARD_LIST_CREATED: 'CURRENT_BOARD_LIST_CREATED',
  CURRENT_BOARD_CARD_CREATED: 'CURRENT_BOARD_CARD_CREATED',
  CURRENT_BOARD_SHOW_FORM: 'CURRENT_BOARD_SHOW_FORM',
  CURRENT_BOARD_SHOW_MEMBERS_FORM: 'CURRENT_BOARD_SHOW_MEMBERS_FORM',
  CURRENT_BOARD_MEMBER_ADDED: 'CURRENT_BOARD_MEMBER_ADDED',
  CURRENT_BOARD_ADD_MEMBER_ERROR: 'CURRENT_BOARD_ADD_MEMBER_ERROR',
  CURRENT_BOARD_EDIT_LIST: 'CURRENT_BOARD_EDIT_LIST',
  CURRENT_BOARD_SHOW_CARD: 'CURRENT_BOARD_SHOW_CARD',
  CURRENT_BOARD_EDIT_CARD: 'CURRENT_BOARD_EDIT_CARD',
  CURRENT_BOARD_SHOW_CARD_FORM_FOR_LIST: 'CURRENT_BOARD_SHOW_CARD_FORM_FOR_LIST',

  LISTS_SHOW_FORM: 'LISTS_SHOW_FORM',

  CARD_MOVE: 'CARD_MOVE',
  CURRENT_CARD_FETHING: 'CURRENT_CARD_FETHING',
  CURRENT_CARD_RESET: 'CURRENT_CARD_RESET',
  CURRENT_CARD_SET: 'CURRENT_CARD_SET',
  CURRENT_CARD_EDIT: 'CURRENT_CARD_EDIT',
  CURRENT_CARD_SHOW_MEMBERS_SELECTOR: 'CURRENT_CARD_SHOW_MEMBERS_SELECTOR',
  CURRENT_CARD_SHOW_TAGS_SELECTOR: 'CURRENT_CARD_SHOW_TAGS_SELECTOR',

  HEADER_SHOW_BOARDS: 'HEADER_SHOW_BOARDS',
};

export default Constants;
