const Constants = {
  SOCKET_CONNECTED: 'SOCKET_CONNECTED',

  USER_CHANNEL_CONNECTED: 'USER_CHANNEL_CONNECTED',
  USER_CHANNEL_DISCONNECTED: 'USER_CHANNEL_DISCONNECTED',

  USERS_CHANNEL_CONNECTED: 'USERS_CHANNEL_CONNECTED',
  USERS_CHANNEL_DISCONNECTED: 'USERS_CHANNEL_DISCONNECTED',

  MATCHES_CHANNEL_CONNECTED: 'MATCHES_CHANNEL_CONNECTED',
  MATCHES_CHANNEL_DISCONNECTED: 'MATCHES_CHANNEL_DISCONNECTED',

  BANCHO_USER_ONLINE: 'BANCHO_USER_ONLINE',
  BANCHO_USER_OFFLINE: 'BANCHO_USER_OFFLINE',
  BANCHO_USER_CHANGE_ACTION: 'BANCHO_USER_CHANGE_ACTION',

  BANCHO_MATCH_CREATE: 'BANCHO_MATCH_CREATE',
  BANCHO_MATCH_UPDATE: 'BANCHO_MATCH_UPDATE',
  BANCHO_MATCH_DESTROY: 'BANCHO_MATCH_DESTROY',

  USER_SIGNED_IN: 'USER_SIGNED_IN',
  CURRENT_USER: 'CURRENT_USER',
  CURRENT_USER_FETCHING: 'CURRENT_USER_FETCHING',
  USER_SIGNED_OUT: 'USER_SIGNED_OUT',
  SESSIONS_ERROR: 'SESSIONS_ERROR',
  REGISTRATIONS_ERROR: 'REGISTRATIONS_ERROR',

  CLOSED_LOGGED_OUT_SNACKBAR: 'CLOSED_LOGGED_OUT_SNACKBAR',

  LEADERBOARD_FETCHING: 'LEADERBOARD_FETCHING',
  LEADERBOARD_RECEIVED: 'LEADERBOARD_RECEIVED',
  LEADERBOARD_ERROR: 'LEADERBOARD_ERROR',

  USER_FETCHING: 'USER_FETCHING',
  USER_RECEIVED: 'USER_RECEIVED',
  USER_ERROR: 'USER_ERROR',

  VERIFY_EMAIL_LOADING: 'VERIFY_EMAIL_LOADING',
  VERIFY_EMAIL_COMPLETED: 'VERIFY_EMAIL_COMPLETED',
  VERIFY_EMAIL_ERROR: 'VERIFY_EMAIL_ERROR',

  RESEND_VERIFICATION_EMAIL_LOADING: 'RESEND_VERIFICATION_EMAIL_LOADING',
  RESEND_VERIFICATION_EMAIL_COMPLETED: 'RESEND_VERIFICATION_EMAIL_COMPLETED',
  RESEND_VERIFICATION_EMAIL_ERROR: 'RESEND_VERIFICATION_EMAIL_ERROR',

  BEATMAPSET_FETCHING: 'BEATMAPSET_FETCHING',
  BEATMAPSET_RECEIVED: 'BEATMAPSET_RECEIVED',
  BEATMAPSET_ERROR: 'BEATMAPSET_ERROR',
  BEATMAPSET_RESET: 'BEATMAPSET_RESET',
};

export default Constants;
